spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/msa?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1q2w3e4r!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 19093
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/